on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
      - run: npm --version
      - name: Install dependencies
        run: npm i
      - name: Install package as local npm-package for testing
        run: npm link
      - name: Run tests
        run: npm run test